// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  biography: dynamic(() => import("./Biography")),
  content_indexx: dynamic(() => import("./ContentIndexx")),
  experiance: dynamic(() => import("./Experiance")),
  heroine: dynamic(() => import("./Heroine")),
  image_block: dynamic(() => import("./ImageBlock")),
  tech_list: dynamic(() => import("./TechList")),
  text_block: dynamic(() => import("./TextBlock")),
};
